version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: |
          (cd app && npm install)
          (cd functions && npm install)
      - run: |
          (cd app && npm run build)
          (cd functions && npm run build)
      - run: |
          (cd app && npm run test:unit)
          (cd functions && npm run test)
