version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm install && cd functions && npm install
      - run: npm run build && cd functions && npm run build
      - run: npm run test:unit && cd functions && npm run test
