version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - run: |
          apt -y update --fix-missing
          apt -y install inkscape unzip
      - checkout
      - run: npm run deps
      - run: npm run format
      - run: npm run build
      - run: npm run lint
      - run: |
          npm run test
          npx codecov
